ifDuos = input("Do you want to see all of the duos in ECRA?(yes/no): ")
if ifDuos == 'yes':
  print("CreepSplotion duos with 14/25 ECRA members.")
  print("CreepSplotion & Ennard")
  print("CreepSplotion & ReapSplotion")
  print("CreepSplotion & Giggles")
  print("CreepSplotion & Quotient")
  print("CreepSplotion & P0ly")
  print("CreepSplotion & UnScr1pted")
  print("CreepSplotion & ClockWise")
  print("CreepSplotion & CreepYT")
  print("CreepSplotion & XRayz")
  print("CreepSplotion & R3zz")
  print("CreepSplotion & R3zz0")
  print("CreepSplotion & Velocity")
  print("CreepSplotion & Anchor")
  print("CreepSplotion & Bee")
  print("ReapSplotion duos with 16/25 ECRA members.")
  print("ReapSplotion & Creep")
  print("ReapSplotion & Ennard")
  print("ReapSplotion & Division")
  print("ReapSplotion & Giggles")
  print("ReapSplotion & Quotient")
  print("ReapSplotion & Finxlly")
  print("ReapSplotion & Quilver")
  print("ReapSplotion & P0ly")
  print("ReapSplotion & aXc3L")
  print("ReapSplotion & CreepYT")
  print("ReapSplotion & R3zz")
  print("ReapSplotion & R3zz0")
  print("ReapSplotion & Anchor")
  print("ReapSplotion & Joc3e")
  print("ReapSplotion & Vee")
  print("ReapSplotion & Bee")
  print("Ennard can duo with 15/25 ECRA members.")
  print("Ennard & Creep")
  print("Ennard & Reap")
  print("Ennard & Division")
  print("Ennard & Giggles")
  print("Ennard & Quotient")
  print("Ennard & Finxlly")
  print("Ennard & P0ly")
  print("Ennard & Temp0rary")
  print("Ennard & UnScr1pted")
  print("Ennard & ClockWise")
  print("Ennard & R3zz0")
  print("Ennard & Velocity")
  print("Ennard & Anchor")
  print("Ennard & Batchi")
  print("Ennard & Joc3e")
  print("Division can duo with 16/25 ECRA members")
  print("Division & ReapSplotion")
  print("Division & Ennard")
  print("Division & Quotient")
  print("Division & Giggles")
  print("Division & Finxlly")
  print("Division & Quilver")
  print("Division & Temp0rary")
  print("Division & UnScr1pted")
  print("Division & aXc3L")
  print("Division & CreepYT")
  print("Division & XRayz")
  print("Division & Anchor")
  print("Division & Batchi")
  print("Division & Joc3e")
  print("Division & Vee")
  print("Division & Bee")
  print("Giggles can duo with 11/25 ECRA members.")
  print("Giggles & CreepSplotion")
  print("Giggles & Ennard")
  print("Giggles & ReapSplotion")
  print("Giggles & Division")
  print("Giggles & Quotient")
  print("Giggles & P0ly")
  print("Giggles & ClockWise")
  print("Giggles & CreepYT")
  print("Giggles & R3zz0")
  print("Giggles & Velocity")
  print("Giggles & Anchor")
  print("Quotient can duo with 12/25 ECRA members.")
  print("Quotient & Creep")
  print("Quotient & Reap")
  print("Quotient & Ennard")
  print("Quotient & Division")
  print("Quotient & P0ly")
  print("Quotient & ClockWise")
  print("Quotient & CreepYT")
  print("Quotient & R3zz")
  print("Quotient & R3zz0")
  print("Quotient & Velocity")
  print("Quotient & Anchor")
  print("Quotient & Joc3e")
  print("Finxlly can duo with 10/25 ECRA members.")
  print("Finxlly & Creep")
  print("Finxlly & Ennard")
  print("Finxlly & Division")
  print("Finxlly & Quotient")
  print("Finxlly & P0ly")
  print("Finxlly & Quilver")
  print("Finxlly & ClockWise")
  print("Finxlly & XRayz")
  print("Finxlly & R3zz")
  print("Finxlly & Batchi")
  print("Quilver can duo with 6/25 ECRA members.")
  print("Quilver & Ennard")
  print("Quilver & P0ly")
  print("Quilver & ClockWise")
  print("Quilver & aXc3L")
  print("Quilver & XRayz")
  print("Quilver & Anchor")
  print("P0ly can duo with 10/25 ECRA members.")
  print("P0ly & Creep")
  print("P0ly & Ennard")
  print("P0ly & Giggles")
  print("P0ly & Quotient")
  print("P0ly & UnScr1pted")
  print("P0ly & ClockWise")
  print("P0ly & CreepYT")
  print("P0ly & R3zz0")
  print("P0ly & Velocity")
  print("P0ly & Anchor")
  print("Temp0rary can duo with 11/25 ECRA members.")
  print("Temp0 & Creep")
  print("Temp0 & Reap")
  print("Temp0 & Division")
  print("Temp0 & Ennard")
  print("Temp0 & Finxlly")
  print("Temp0 & aXc3L")
  print("Temp0 & R3zz")
  print("Temp0 & Batchi")
  print("Temp0 & Joc3e")
  print("Temp0 & Bee")
  print("Temp0 & Vee")
  print("UnScr1pted can duo with every ECRA member.")
  print("ClockWise can duo with every ECRA member.")
  print("aXc3L can duo with every ECRA member.")
  print("CreepYT can duo with every member except Temp0rary")
  print("XRayz can duo with every member except Dash and XxFun")
  print("R3zz can duo with every member except Batchi, Joc3e, and Bee.")
  print("R3zz0 can duo with every ECRA member.")
  print("Velocity can duo with every member except those under rank 20.")
  print("Anchor can duo with every ECRA member.")
